# Generated by Django 5.0.7 on 2024-08-22 04:39

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_useraddress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.IntegerField(verbose_name='مبلغ کل')),
                ('is_paid', models.BooleanField(default=False, verbose_name='وضعیت پرداخت ')),
                ('accepted', models.BooleanField(blank=True, default=False, verbose_name='تایید سفارش')),
                ('sended', models.BooleanField(blank=True, default=False, verbose_name='ارسال شده')),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True)),
                ('delivered', models.BooleanField(blank=True, default=False, verbose_name='تحویل داده شده')),
                ('returned', models.BooleanField(blank=True, default=False, verbose_name='مرجوعی')),
                ('Cancellation', models.BooleanField(blank=True, default=False, verbose_name='لغو شده')),
                ('shipping_cost', models.PositiveIntegerField(default=100000)),
                ('addresses', models.ManyToManyField(blank=True, related_name='orders', to='users.useraddress', verbose_name='آدرس\u200c')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cart', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
    ]
